/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twer' at '9/7/14 7:04 PM' with Gradle 1.10
 *
 * @author twer, @date 9/7/14 7:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
